include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
#obj-y   +=  otm9605a_dsi_vdo_cs.o
#obj-y   +=  otm9605a_dsi_vdo_dijing.o
obj-y   +=  r69338_hd720_dsi_vdo_jdi_y70.o
